/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Computer.glb -o src/components/Computer.jsx -k -K -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Computer(props) {
  const { nodes, materials } = useGLTF('/models/Computer.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh name="Comp_Mouse" geometry={nodes.Comp_Mouse.geometry} material={materials.lambert3SG} />
        <mesh name="Monitor" geometry={nodes.Monitor.geometry} material={materials.lambert3SG} />
        <mesh name="Drive" geometry={nodes.Drive.geometry} material={materials.lambert3SG} />
        <group name="System_unit">
          <mesh name="System_unit_1" geometry={nodes.System_unit_1.geometry} material={materials.lambert3SG} />
          <mesh name="System_unit_1_1" geometry={nodes.System_unit_1_1.geometry} material={materials.initialShadingGroup} />
        </group>
        <mesh name="Keyboard1" geometry={nodes.Keyboard1.geometry} material={materials.lambert3SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Computer.glb')
