/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Home Doormat.glb -o src/components/HomeModel.jsx -k -K -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function HomeModel(props) {
  const { nodes, materials } = useGLTF('/models/Home Doormat.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <group name="Node">
          <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={materials.mat18} />
          <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat23} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Home Doormat.glb')
