/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Office Phone.glb -o src/components/Phone2.jsx -k -K -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Phone2(props) {
  const { nodes, materials } = useGLTF('/models/Office Phone.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Phone_Body" position={[-0.46, -1.577, -0.973]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="Phone_Body_1" geometry={nodes.Phone_Body_1.geometry} material={materials['Light grey']} />
            <mesh name="Phone_Body_2" geometry={nodes.Phone_Body_2.geometry} material={materials['Grey Plastic']} />
            <mesh name="Phone_Body_3" geometry={nodes.Phone_Body_3.geometry} material={materials.Screen} />
            <mesh name="Phone_Body_4" geometry={nodes.Phone_Body_4.geometry} material={materials['Dark Grey Plastic']} />
            <mesh name="Handle" geometry={nodes.Handle.geometry} material={materials['Dark Grey Plastic']} position={[-0.016, -0.008, 0.02]} rotation={[-0.374, 0, Math.PI / 2]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Office Phone.glb')
