/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Phone.glb -o src/components/Phone.jsx -k -K -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Phone(props) {
  const { nodes, materials } = useGLTF('/models/Phone.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh name="Phone" geometry={nodes.Phone.geometry} material={materials.Mat} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Phone.glb')
